config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :courses, only: [ :index, :show ] do
    resources :bookmarks, only: [ :new, :create, :destroy ]
    resources :course_reviews, only: [ :index, :new, :create ]

  end

  get 'users/edit_avatar' => 'users#edit_avatar', :as => :edit_avatar
  post 'users/edit_avatar' => 'users#new_avatar', :as => :new_avatar


  resources :users, only: [:show] do
    resources :course_reviews, only: [ :destroy ]
  end

  get "/categories" => "courses#categories"



  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  has_many :course_reviews
  has_many :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @search_input = params.dig(:criteria, :search)
    @error = ""
    @levels = params.dig(:criteria, :knowledge_level)
    @platforms = params.dig(:criteria, :platform)
    @prices = params.dig(:criteria, :price)
    @completion_times = params.dig(:criteria, :completion_time)
    @reviews = CourseReview.where(user_id: current_user.id)
    @categories = CategoryHelper.categories
    if params[:id].to_i != current_user.id
      redirect_to root_path(error: "Account does not belong to you")
    else
      @user = User.find(params[:id])
      @reviews = CourseReview.where(user_id: params[:id])
      bookmark_ids = Bookmark.where(user_id: params[:id])
      @courses = []
      @reviews
      bookmark_ids.each do |id|
        @courses << Course.where(id: id.course_id)
      end
    end
  end

  def edit_avatar
    @user = User.new
  end

  def new_avatar
    @user = User.where(id: current_user.id)
    @user.update(user_params)
    redirect_to user_path(current_user.id)
  end


  def edit
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit( :avatar)
  end
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit_avatar.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4" style="margin-top: 50px;">
      <div class="box">
        <%= simple_form_for(@user, :url => "/users/edit_avatar") do |f| %>
          <div class="form-group">
            <div class="flex">
              <%= f.input :avatar %>
              <%= f.input :avatar_cache, as: :hidden %>
            </div>
          </div>
          <%= f.button :submit, "Add new avatar picture", class: "button-green-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 info-container">
      <div class="card-tab">
        <div class="tabs">
          <a class="tab active" id="tab1">
            <h3>Bookmarks</h3>
            <p><%=@courses.size%></p>
          </a>
          <a class="tab" id="tab2">
            <h3>Reviews</h3>
            <p><%=@reviews.size%></p>
          </a>
        </div>
        <div class="tab-content box" style="margin-top: 0px;">
          <div id="tab1-content">
            <% if @courses.flatten.empty? %>
              <h3 class="heading">No bookmarks yet?</h3>
              <h3 class="subtitle" style="font-size: 20px; margin-bottom: 24px;">Begin adding some!</h3>
              <div>
                <%= link_to "See all courses", courses_path, class: "button-green-secondary" %>
              </div>
            <% else %>
              <%@courses.flatten.each do |course|%>
                <div class="card-result">
                  <div class="header">
                    <h3 class="heading"><%=course.title%></h3>
                  </div>
                  <div class="horizontal-icons">
                    <div class="icon-next icon-inline" style="margin-top: 0px;">
                      <i class="fas fa-graduation-cap"></i>
                      <p><%= course.knowledge_level.capitalize %></p>
                    </div>
                    <div class="icon-next icon-inline" style="margin-top: 0px;">
                      <i class="far fa-clock"></i>
                      <p><%= course.duration%></p>
                    </div>
                    <div class="icon-next icon-inline" style="margin-top: 0px;">
                      <i class="fas fa-coins"></i>
                      <p><%= "#{course.price} #{course.price_unit}" %></p>
                    </div>
                  </div>
                  <div class="content" >
                    <p class="paragraph" style= "margin-bottom: 20px;"><%= truncate(course.description, length: 400, escape: false) %></p>
                    <div class="small-placeholder"></div>
                    <%= link_to("See Details", course_path(course), class: "button-green-secondary") %>
                  </div>
                  <hr>
                </div>
              <% end %>
            <% end %>
          </div>
          <div id="tab2-content" class="hide">
            <% if @reviews.empty? %>
              <h3 class="heading">No reviews yet?</h3>
              <h3 class="subtitle" style="font-size: 20px; margin-bottom: 24px;">Start completing some courses!</h3>
              <div>
                <%= link_to "See all courses", courses_path, class: "button-green-secondary" %>
              </div>
            <% else %>
              <% @reviews.each do |review|%>
                <div class="review-overview">

                  <div class="coursename">
                    <% course = Course.all.find(review.course_id) %>
                    <h3 class="subtitle" style="font-style: italic; font-size: 18px;">Course: <%= course.title %> </h3>
                  </div>
                  <div class="flex">
                    <h3 class="heading"><%= review.title %></h3>
                    <div class="stars">
                      <% t = review.rating.to_i %>
                      <% t.times do %>
                        <i class="fas fa-star"></i>
                      <% end %>
                      <% (5-t).times do %>
                        <i class="far fa-star"></i>
                      <% end %>
                    </div>
                    <i class="delete-icon"><%= link_to("", user_course_review_path(current_user, review), method: :delete, :class => "fas fa-trash-alt") %></i>
                  </div>
                  <p class="paragraph"><%= review.content %> </p>
                  <div class="small-placeholder"></div>
                  <%= link_to "Visit Course", course_path(course), class: "button-green-secondary" %>
                </div>
                <div class="medium-placeholder">
                </div>
                <hr>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <div class="col-xs-12 col-sm-4 contact-container">
      <div class="box">
        <div class="card-avatar">
          <div class="card-avatar-content">
              <%= cl_image_tag(current_user.avatar.filename, class: "avatar-md-lg") %>
            <h2>Hey <%= @user.name %>!</h2>
            <p>How are you today?</p>
          </div>
        </div>
        <hr>
        <div class="card-result">
          <div class="card-edit-user">
            <div class="header">
              <h3 class="heading">Edit your profile:</h3>
              <div class="flex">
                <i class="fas fa-unlock-alt icon"></i>
                <p><%= link_to "Change your password", edit_user_registration_path, class: "link-user" %></p>
              </div>
              <div class="flex">
                <i class="fas fa-user-circle icon"></i>
                <p><%= link_to "Change your avatar", edit_avatar_path, class: "link-user" %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="box">
        <div class="col-xs-12">
          <% i = 0 %>
          <% @categories.each do |category| %>
            <%= render 'shared/category', category_name: category[1][0], image: category[1][1], count: category[1][2]  %>
            <% i += 1 %>
            <% break if i == 2 %>
          <% end %>


        </div>

        <div>
          <%= link_to "See all", categories_path, class: "button-green-secondary" %>
        <hr>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>