config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :courses, only: [ :index, :show ] do
    resources :bookmarks, only: [ :new, :create, :destroy ]
    resources :course_reviews, only: [ :index, :new, :create ]

  end

  get 'users/edit_avatar' => 'users#edit_avatar', :as => :edit_avatar
  post 'users/edit_avatar' => 'users#new_avatar', :as => :new_avatar


  resources :users, only: [:show] do
    resources :course_reviews, only: [ :destroy ]
  end

  get "/categories" => "courses#categories"



  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_category.html.erb
  <%= link_to courses_path(criteria: {search: "#{category_name}"}), style: "text-decoration: none;" do %>
    <div class="box category-box">
      <div class="category-card">
        <div class="category-card-content">
            <div class="category-card-image" style="background: linear-gradient(
        rgba(220,220,220, 0.3),
        rgba(220,220,220, 0.3)), url(<%= image_path(image) %> );">

            </div>
            <div class="category-card-footer">
                <h3>  <%=  "#{category_name}"  %> </h3>
                <p><%= "#{count} courses" %> </p>
            </div>
        <!-- category-card-content -->
        </div>
      </div>
    <!-- Box -->
    </div>
  <% end %>
<!-- col -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-section">
    <h3>
      About us
    </h3>
    <div>
      <p>
       We are constantly improving our platform in order to match customers with the best courses!
      </p>
    </div>
  </div>

  <div class="footer-section">
    <h3>
      Get in touch
    </h3>
    <div class="flex">
      <div class="icons-rolling" target="_blank">
        <a href="#"> <i class="fab fa-facebook-f"></i> </a>
      </div>
      <div class="icons-rolling">
        <a href="mailto:contact@coursehunt.io" target="_blank"> <i class="fas fa-envelope"></i> </a>
      </div>
      <div class="icons-rolling">
        <a href="https://github.com/alexreichhardt/courseapp" target="_blank"> <i class="fab fa-github"></i> </a>
      </div>
      <div class="icons-rolling" target="_blank">
        <a href="#"> <i class="fab fa-linkedin"></i> </a>
      </div>
    </div>
  </div>

  <div class="footer-section">
    <h3>
      Our Partners
    </h3>
    <div class="footer-links flex">
      <div>
        <div>
          <div>
            <a href="https://www.udemy.com/" target="_blank">Udemy</a>
          </div>
          <div>
            <a href="https://www.edx.org/" target="_blank">EdX</a>
          </div>
        </div>
      </div>
      <div style="margin-left: 15%;">
        <div>
          <div>
            <a href="https://www.futurelearn.com/" target="_blank">Futurelearn</a>
          </div>
          <div>
            <a href="https://eu.udacity.com/" target="_blank">Udacity</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand link" do %>
      <div class="flex">
        <%= image_tag "lionblue.png", height: 50, class:"white" %>
        <h3 class="coursehunt-blue" style="padding-left: 20px; margin-top: 11px;">Coursehunt.io</h3>
      </div>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <%= link_to 'Categories', categories_path, class: "navbar-wagon-item navbar-wagon-link navbar-link-wrapper" %>
    <%if !user_signed_in?%>
        <%= link_to 'Login', new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-link-wrapper"%>
    <%end%>


  <!-- Avatar with dropdown menu -->
  <%if user_signed_in?%>
  <div class="navbar-wagon-item">
    <div class="dropdown">
        <img src='<%= current_user.avatar %>' class="avatar-sm dropdown-toggle" id="navbar-airnbboat-menu" data-toggle="dropdown">
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link"%></li>
      </ul>
    </div>
  </div>
  <%end%>
    </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>