config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :courses, only: [ :index, :show ] do
    resources :bookmarks, only: [ :new, :create, :destroy ]
    resources :course_reviews, only: [ :index, :new, :create ]

  end

  get 'users/edit_avatar' => 'users#edit_avatar', :as => :edit_avatar
  post 'users/edit_avatar' => 'users#new_avatar', :as => :new_avatar


  resources :users, only: [:show] do
    resources :course_reviews, only: [ :destroy ]
  end

  get "/categories" => "courses#categories"



  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index, :categories]


  def index
    @search_input = params.dig(:criteria, :search)
    @error = nil
    @levels = params.dig(:criteria, :knowledge_level)
    @platforms = params.dig(:criteria, :platform)
    @prices = params.dig(:criteria, :price)
    @completion_times = params.dig(:criteria, :completion_time)
    @categories = CategoryHelper.categories
    @top_categories = CategoryHelper.top_categories

    if @search_input.blank?
      # display all courses if user makes no input
      @courses = Course.includes(:bookmarks).page(params[:page]).per(10)

    elsif Course.search_global(@search_input).empty?
      @error = "The exact course you searched for could not be found, but here are some other courses you may be interested in."
      @courses = Course.includes(:bookmarks).page(params[:page]).per(10)
    else
      # otherwise apply use search alogrithm
      @courses = Course.search_global(@search_input)
      @courses = @courses.page(params[:page]).per(10)
    end

    # FILTERS:
    # knowledge level
    if params.dig(:criteria, :knowledge_level)
        selected_options = params[:criteria][:knowledge_level].reject(&:blank?)
      if selected_options.blank?
        selected_options = ["beginner", "intermediate", "advanced"]
      end
      @courses = @courses.where(knowledge_level: [selected_options])
    end

    # platform
    if params.dig(:criteria, :platform)
      selected_options = params[:criteria][:platform].reject(&:blank?)
      if selected_options.blank?
        selected_options = ["udemy", "udacity", "edx"]
      end
      @courses = @courses.where(platform: selected_options)
    end

    # price

    # if @prices
    if params.dig(:criteria, :price)
      selected_options = params[:criteria][:price].reject(&:blank?)
      if selected_options.blank? || selected_options.count == 2
        @courses = @courses # .where("price >= 0")
      elsif selected_options[0] == "Paid"
        @courses = @courses.where("price > 0 OR price is null" )
      elsif selected_options[0] == "Free"
        @courses = @courses.where("price = 0")
      end
    end
    # end

    # completion time
    if @completion_times
      selected_options = params[:criteria][:completion_time]&.reject(&:blank?)
      if selected_options[0] == "> 1 week"
        @courses = @courses.where("completion_time = 'long'")
      elsif selected_options[0] == "< 1 week"
        @courses = @courses.where("completion_time = 'short'")
      # else if selected_options.blank? || selected_options.count == 2
      end
    end
  end



  def show

    @search_input = params.dig(:criteria, :search)
    @error = ""
    @levels = params.dig(:criteria, :knowledge_level)
    @platforms = params.dig(:criteria, :platform)
    @prices = params.dig(:criteria, :price)
    @completion_times = params.dig(:criteria, :completion_time)

    @course = Course.find(params[:id])
    @bookmarked = false
    @reviews = CourseReview.where(course_id: params[:id])
    if user_signed_in?
      bookmark = Bookmark.where(user_id: current_user.id, course_id: params[:id])
      if !bookmark.empty?
        @bookmarked = true
      end
    end
  end

  def categories
    @categories = CategoryHelper.categories
    @top_categories_count = CategoryHelper.top_categories
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
  def label_select(key, filter, value)
    html = nil
    if filter&.include?(value)
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[#{key}][]" id="criteria_#{key}_#{value}" checked>
        <label class="collection_check_boxes category-choice active" for="criteria_#{key}_#{value}">
          #{value.capitalize}
        </label>
      HTML
    else
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[#{key}][]" id="criteria_#{key}_#{value}">
        <label class="collection_check_boxes category-choice" for="criteria_#{key}_#{value}">
          #{value.capitalize}
        </label>
      HTML
    end
    html.html_safe
  end

  def label_select_filter_mobile(key, filter, value)
    html = nil
    if filter&.include?(value)
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[#{key}][]" id="criteria_#{key}_#{value}" checked>
        <label class="collection_check_boxes category-choice-mobile active" for="criteria_#{key}_#{value}">
          #{value.capitalize}
        </label>
      HTML
    else
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[#{key}][]" id="criteria_#{key}_#{value}">
        <label class="collection_check_boxes category-choice-mobile" for="criteria_#{key}_#{value}">
          #{value.capitalize}
        </label>
      HTML
    end
    html.html_safe
  end

  def course_attributes(instructor, number_of_ratings, avg_rating, language, active)
    active = active?(active)
    html = nil
    if number_of_ratings < 3
      html = <<-HTML
        <div class="center-align-3-elements">
          <p style="margin-bottom: 4px;">Instructor<p>
          <p style= "font-weight: 300;">#{instructor.capitalize}</p>
        </div>
        <div class="center-align-3-elements">
          <p style="margin-bottom: 4px;">Language<p>
          <p style= "font-weight: 300;">#{language.capitalize}</p>
        </div>
        <div class="center-align-3-elements">
          <p style="margin-bottom: 4px;">Available now<p>
            #{active}
        </div>
      HTML
    else
      html = <<-HTML
        <div class="center-align-4-elements">
          <p style="margin-bottom: 4px;">Instructor<p>
          <p style= "font-weight: 300;">#{instructor.capitalize}</p>
        </div>
        <div class="center-align-4-elements">
          <p style="margin-bottom: 4px;">Language<p>
          <p style= "font-weight: 300;">#{language.capitalize}</p>
        </div>
        <div class="center-align-4-elements">
          <p style="margin-bottom: 4px;">Available now<p>
          #{active}
        </div>
        <div class="center-align-4-elements">
          <p style="margin-bottom: 4px;">Avg. rating<p>
          <p style= "font-weight: 300;"> #{avg_rating}  </p>
        </div>
      HTML
    end
    html.html_safe
  end

  def active?(input)
    html = nil
    if input == true
      html = <<-HTML
        <p style= "font-weight: 300;">Yes</p>
      HTML
    else
      html = <<-HTML
        <p style= "font-weight: 300;">No</p>
      HTML
      html.html_safe
    end
  end




  ###### Helper for home page #########
  def label_select_home(filter, value)
    html = nil
    if filter&.include?(value)
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[knowledge_level][]" id="criteria_knowledge_level_#{value}" checked>
        <label class="collection_check_boxes category-choice-home active" for="criteria_knowledge_level_#{value}">
          #{value.capitalize}
        </label>
      HTML
    else
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[knowledge_level][]" id="criteria_knowledge_level_#{value}">
        <label class="collection_check_boxes category-choice-home" for="criteria_knowledge_level_#{value}">
          #{value.capitalize}
        </label>
      HTML
    end
    html.html_safe
  end

   # price filter
  def label_select_price_home(filter, value)
    html = nil
    if filter&.include?(value)
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[price][]" id="criteria_price_#{value}" checked>
        <label class="collection_check_boxes category-choice-home active" for="criteria_price_#{value}">
          #{value}
        </label>
      HTML
    else
      html = <<-HTML
        <input class="form-check-input hidden required" type="checkbox" value="#{value}" name="criteria[price][]" id="criteria_price_#{value}">
        <label class="collection_check_boxes category-choice-home" for="criteria_price_#{value}">
          #{value}
        </label>
      HTML
    end
    html.html_safe
  end

######## link back ######
  def check_levels(levels)
    if levels == ""
      levels = []
    end
  end

  def build_criteria_hash(search, levels, platforms, prices, completion_times)

    criteria_hash = {}

    criteria_hash[:search] = search
    criteria_hash[:knowledge_level] = levels if !levels&.blank?
    criteria_hash[:platform] = platforms if !platforms&.blank?
    criteria_hash[:price] = prices if !prices&.blank?
    criteria_hash[:completion_time] = completion_times if !completion_times&.blank?

    criteria_hash

  end

  def link_to_toggle_course_bookmark(course)

    url_create = course_bookmarks_path(course)

    url_session = new_user_session_path(redirect_to: courses_path(criteria: build_criteria_hash(@search_input, @levels, @platforms, @prices, @completion_times)))

    if !user_signed_in?
      link_to_with_icon('far fa-bookmark', '', url_session, {
          method: 'GET',
          remote: false,
          id: "bookmark-icon",
          class: "single-icon-index",
        })

    else
      bookmark = Bookmark.find_by(course_id: course.id, user_id: current_user.id)
      if course.bookmarked?(current_user.id)
        url_destroy = course_bookmark_path(course.id, bookmark.id)
        link_to_with_icon('fas fa-bookmark', '', url_destroy, {
            method: 'DELETE',
            remote: true,
            id: "bookmark-icon",
            class: "single-icon-index",
            })
      else
        link_to_with_icon('far fa-bookmark', '', url_create, {
            method: 'POST',
            remote: true,
            id: "bookmark-icon",
            class: "single-icon-index",
          })
      end
    end
  end

  def link_to_with_icon(icon_css, title, url, options = {})
        icon = content_tag(:i, nil, class: icon_css)
        title_with_icon = icon << ' '.html_safe << h(title)
        link_to(title_with_icon, url, options)
  end
end

app/views/courses/categories.html.erb
<!-- blue header -->
  <div class="wrapper-header">
    <div class="container">
      <div class="header-content">
        <h1>Browse all categories</h1>
        <p>Explore different fields of computer science such as Software Engineering, Computer Security or Database Management</p>
      </div>
    </div>
  </div>


  <div class="container-categories">
     <div class="medium-placeholder">
    </div>
    <div class="container">
      <div class="row">
        <div class="categories-section">
          <div class="category-header">
            <i class="far fa-heart"></i>
            <p>Most Popular</p>
          </div>
          <hr>
          <div class="category-row">
            <% @top_categories_count.each do |category| %>
              <div class="col-xs-12 col-md-6 col-lg-3">
                <%= render 'shared/category', category_name: category[1][0], image: category[1][1], count: category[1][2]  %>
              </div>
            <% end %>
          </div>
        </div>


        <div class="categories-section">
          <div class="category-header">
            <i class="fas fa-globe"></i>
            <p>All</p>
          </div>
          <hr>
          <div class="category-row">
            <% @categories.each do |category| %>
              <div class="col-xs-12 col-md-6 col-lg-3">
                <%= render 'shared/category', category_name: category[1][0], image: category[1][1], count: category[1][2]
                %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <!-- container categories -->
  </div style="margin-bottom: 50px;  "    >

  <div class="picture" style="display:none;">
    <%=image_tag("preview") %>
  </div>

app/views/courses/index.html.erb
<% if @error != nil %>
  <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%=@error%>
  </div>
<%end%>
<div class="container fullwidth">
  <div class="row">
    <!-- left side -->
    <div class="col-xs-0 col-sm-3 col-md-2">
      <div class="filter-container filters-card">
        <%= simple_form_for :criteria, url: courses_path, :method => :get do |f| %>

        <div class="small-placeholder"></div>

        <ul class="filter ul-reset">
          <li class="filter-item">
            <h3 class="filter-item-inner-heading minus"> Knowledge level
            </h3>
            <ul class="filter-attribute-list ul-reset">
              <div class="filter-attribute-list-inner">
                <li class="filter-attribute-item">
                  <%= label_select("knowledge_level", @levels, "beginner") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("knowledge_level", @levels, "intermediate") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("knowledge_level", @levels, "advanced") %>
                </li>
              </div>
            </ul>
          </li>
          <li class="filter-item">
            <h3 class="filter-item-inner-heading minus"> Platform
            </h3>
            <ul class="filter-attribute-list ul-reset">
              <div class="filter-attribute-list-inner">
                <li class="filter-attribute-item">
                  <%= label_select("platform", @platforms, "udemy") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("platform", @platforms, "udacity") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("platform", @platforms, "edx") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("platform", @platforms, "futurelearn") %>
                </li>
              </div>
            </ul>
          </li>

          <li class="filter-item">
            <h3 class="filter-item-inner-heading minus"> Price
            </h3>
            <ul class="filter-attribute-list ul-reset">
              <div class="filter-attribute-list-inner">
                <li class="filter-attribute-item">
                  <%= label_select("price", @prices, "Free") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("price",@prices, "Paid") %>
                </li>
              </div>
            </ul>
          </li>

          <li class="filter-item">
            <h3 class="filter-item-inner-heading minus"> Completion time
            </h3>
            <ul class="filter-attribute-list ul-reset">
              <div class="filter-attribute-list-inner">
                <li class="filter-attribute-item">
                  <%= label_select("completion_time", @completion_times, "> 1 week") %>
                </li>
                <li class="filter-attribute-item">
                  <%= label_select("completion_time", @completion_times, "< 1 week") %>
                </li>
              </div>
            </ul>
          </li>
        </ul>
        <div>
          <%= f.hidden_field :search, value: @search_input %>

          <!-- submit button -->
          <%= f.button :submit, "Search", class: "button-white-sidebar"%>
          <%= button_to "Clear", "#", class: "uncheck-all btn button-white-sidebar-inv" %>
        </div>
        <% end %>
        <!-- filter-container -->
      </div>
      <!-- COL LEFT SIDE -->
    </div>

    <!-- right side -->
    <div class="col-xs-12 col-sm-9 col-md-7">
      <div class="container1">
        <!-- search -->
        <div class="box" id="index-search-box">
          <div class="flex flex-mobile">
          <%= simple_form_for :criteria, url: courses_path,
                wrapper: :inline_form,
                html: { class: "form-inline index-search-form width-search-mobile"},
                wrapper_mappings: {
                boolean: :inline_boolean}, :method => :get do |f| %>
                <%= f.input :search, id: "search", as: :string,
                    input_html: {
                      class: "awesomplete",
                      data: {
                      categories: Course::CATEGORIES.join(", ")
                      },
                      value: @search_input || ''
                    }
                  %>


            <%= f.button :submit, "Hunt", class: "button-green-primary button-mobile"%>
            <% end %>
            <div class="filter-mobile" >
              <button type="button" class="button-mobile-filter" data-toggle="modal" data-target="#exampleModalCenter">
                Filter
              </button>
           </div>
          </div>
        </div>

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content box">
        <div class="modal-header">
          <div class="flex modal-flex">
          <h3 class="heading" id="exampleModalLongTitle">Filter Results</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
        <div class="modal-body">
          <%= simple_form_for :criteria, url: courses_path, :method => :get do |f| %>
                          <div>
              <h3 class="subheading-small">Indicate your skill level here:</h3>
              <div class="flex" style="min-height: 50px;">
                <%= label_select_filter_mobile("knowledge_level", @levels, "beginner") %>
                <%= label_select_filter_mobile("knowledge_level", @levels, "intermediate") %>
                <%= label_select_filter_mobile("knowledge_level", @levels, "advanced") %>
              </div>
            </div>
            <div>
              <h3 class="subheading-small" style="margin-bottom: 12px;">Which platform(s) do you prefer?</h3>
              <div class="flex" style="min-height: 25px;">
                <%= label_select_filter_mobile("platform", @platforms, "udemy") %>
                <%= label_select_filter_mobile("platform", @platforms, "udacity") %>
              </div>
              <div class="flex" style="min-height: 25px; margin-bottom: 12px;" >
                <%= label_select_filter_mobile("platform", @platforms, "edx") %>
                <%= label_select_filter_mobile("platform", @platforms, "futurelearn") %>
              </div>
            </div>
            <div>
              <h3 class="subheading-small" >What's your budget?</h3>
              <div class="flex" style="min-height: 50px;">
                <%= label_select_filter_mobile("price", @prices, "Free") %>
                <%= label_select_filter_mobile("price", @prices, "Paid") %>
              </div>
            </div>
            <div>
              <h3 class="subheading-small">Please indicate completion time</h3>
              <div class="flex" style="min-height:50px;">
                <%= label_select_filter_mobile("completion_time", @completion_times, "> 1 week") %>
                <%= label_select_filter_mobile("completion_time", @completion_times, "< 1 week") %>
              </div>
            </div>

            <div class="modal-footer align-button-right">
              <%= f.button :submit, "Specify Search", class: "button-green-primary"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

          <!-- result information -->
        <div class="result-title">
          <p> <%= page_entries_info @courses, entry_name: 'courses' %> </p>
        </div>

      </div>


      <% @courses.each do |course| %>
      <% course_sec = "course" + course.id.to_s  %>
        <section id="<%=course_sec%>">
          <div class="box-flex-index card-medium first-card">
            <div class="row">
              <div class="col-xs-9" >
                <h3 class="heading"><%=course.title%></h3>
              </div>

              <div class="col-xs-1 col-xs-offset-1 col-sm-1 col-sm-offset-2 bookmark-index-padding">
                <div class="bookmark-background">
                <%= link_to_toggle_course_bookmark(course) %>
                </div>
              </div>
            </div>

            <div class="row display-table-cell">
                <div class="card-content-left col-xs-12 col-sm-9">
                  <% desc_as_text = Truncato.truncate course.description, max_length: 400 %>
                  <%= desc_as_text.html_safe %>
                  <!-- desc_as_text.truncate(27, escape: false) -->
                </div>
                <div class="card-content-right col-xs-12 col-sm-3">
                  <div class="content-right-attributes">
                    <% unless course.knowledge_level.nil? %>
                    <div class="icon-next">
                      <i class="fas fa-graduation-cap"></i>
                      <p><%= course.knowledge_level.capitalize %></p>
                    </div>
                    <% end %>
                    <% unless course.duration.nil? %>
                    <div class="icon-next">
                      <i class="far fa-clock"></i>
                      <p><%= course.duration%></p>
                    </div>
                    <% end %>
                    <% unless course.price.nil? %>
                    <div class="icon-next">
                      <i class="fas fa-coins"></i>
                      <p><%= "#{course.price} #{course.price_unit}" %></p>
                    </div>
                    <% end %>
                    <% unless course.avg_rating.nil? %>
                    <div class="icon-next">
                      <i class="fas fa-star"></i>
                      <p><%= course.avg_rating %></p>
                    </div>
                    <% end %>
                  </div>
                  <div class="card-button">
                    <%= link_to("See Details", course_path(course, criteria: {search: @search_input, knowledge_level: @levels, platform: @platforms, price: @prices, completion_time: @completion_times}), class: "button-green-primary") %>
                  </div>
                </div>
              </div>
            </section>
          <% end %>


       <!-- container1 -->
         <div class="indent-next-buttons">
          <%= link_to_previous_page @courses, 'Previous Page', class: "button-red-secondary" %>
          <%= link_to_next_page @courses, 'Next Page', class: "button-green-secondary" %>
        </div>
      <!-- CONTAINER -->
      </div>

      <div class="col-md-3 show-large cards-container">

        <% @top_categories.each do |category| %>
            <%= render 'shared/category', category_name: category[1][0], image: category[1][1], count: category[1][2]  %>
        <% end %>

      </div>
      <!-- col -->
    </div>
    <!-- row -->
  </div>
<!-- container special -->
</div>
<!-- results row -->

app/views/courses/show.html.erb
<div class="container">

  <div class="course-show-row row">
    <!-- left side -->
    <div class="col-xs-12 col-md-8">
      <!-- for css of the left side -->
      <div class="box">
        <div class="flex align-horizontal">
          <p><%= @course.platform.capitalize %> online course<p>
          <%= link_to_toggle_course_bookmark(@course) %>
        </div>
        <h1 class="title"><%= @course.title %></h1>
        <!-- course description -->
        <div class="course-description">
          <!-- Print subtitle if existing -->
          <% unless @course.subtitle.nil? %>
            <h3 class="subtitle"><%= @course.subtitle %> </h3>
          <% end %>
          <div class="paragraph truncate">
            <p><%= @course.description.html_safe %></p>
          </div>
        </div>
        <div class="course-attributes">
          <div class="box box-horizontal">
            <% if @course.instructor["instructors"].nil? %>
              <%= course_attributes("Max Mustermann", @course.sum_ratings, @course.avg_rating, @course.language, @course.active) %>
            <% else %>
              <%= course_attributes(@course.instructor["instructors"][0]["name"], @course.sum_ratings, @course.avg_rating, @course.language, @course.active) %>
            <%end%>
          </div>
        </div>
        <hr>
        <!-- reviews -->
        <div>
          <% if @reviews.empty? %>
            <h3 class="heading">No reviews yet</h3>
            <h3 class="subtitle" style="font-size: 20px; margin-bottom: 24px;">Be the first!</h3>
            <div>
              <%= link_to "Add Review", new_course_course_review_path(@course.id), class: "button-green-secondary" %>
            </div>
          <% else %>
            <h3 class="heading">Reviews (<%= @reviews.count %>)</h3>
          <% end %>
          <% @reviews.each do |review|%>
            <div class="flex">
              <div class="author">
                <% author_id = review.user_id %>
                <% author = User.find(author_id) %>
               <%=  cl_image_tag(author.avatar, class: "avatar-md")  %>
                <p class="paragraph" style="text-align: center; margin-top: 8px;"><%= author.name %></p>
              </div>
              <div class="review-content">
                <div class="flex">
                  <h3 style= "font-size: 24px; margin-top: 11px"><%= review.title %></h3>
                  <div class="stars">
                    <% t = review.rating.to_i %>
                    <% t.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                    <% (5-t).times do %>
                      <i class="far fa-star"></i>
                    <% end %>
                  </div>
                </div>
                  <p><%= review.content %> </p>
              </div>

            </div>
            <div class="medium-placeholder">
            </div>
          <%end%>
        <!-- reviews -->
        </div>
      <!-- for css of the left side -->
      </div>
    <!-- left side -->
    </div>

    <!-- card on the right side -->
    <div class="col-xs-12 col-md-4 make-it-stick">
      <div class="box course-details">
        <div class="course-image">
          <% case @course.platform %>
          <% when "udemy" %>
            <%= image_tag("udemy-logo", class: "course-image") %>
          <% when "udacity" %>
            <%= image_tag("udacity-logo", class: "course-image") %>
          <% when "edx" %>
            <%= image_tag("edx-logo", class: "course-image") %>
          <% when "futurelearn" %>
            <%= image_tag("futurelearn-logo", class: "course-image") %>
          <% end %>
        </div>
        <hr>
        <ul style="margin-bottom: 15px;">
          <li class= "list-style">
            <i class="fas fa-coins icon"></i>
            Price: <%= @course.price %>
          </li>
          <% unless @course.duration == "" || @course.duration == "0" %>
            <li class= "list-style">
              <i class="far fa-clock icon"></i>
              <%= "#{@course.duration}"%>
            </li>
          <% end %>
          <li class= "list-style">
            <i class="fas fa-graduation-cap icon"></i>
            <%=  @course.knowledge_level.capitalize unless @course.knowledge_level.blank? %>
          </li>
          <li class= "list-style">
            <i class="fas fa-external-link-square-alt icon"></i>
            Offering platform: <%= @course.platform %>
          </li>
          <% course_id = @course.id %>
          <% bookmarks = Bookmark.where(course_id: course_id) %>
          <% num_of_bookmarks = bookmarks.count %>
            <div class="bookmark-rating">
              <p class ="paragraph">Previously bookmarked by <%= num_of_bookmarks %> users</p>
            </div>
        </ul>
        <%= link_to "Start now on #{@course.platform}", @course.url, class: "button-green-primary", target: "_blank" %>
        <div class="add-review">
          <p>Already took it?</p>
          <%= link_to "Add Review", new_course_course_review_path(@course.id), class: "button-green-secondary" %>
        <hr>

           <%= link_to "Back to Results", courses_path(criteria: build_criteria_hash(@search_input, @levels, @platforms, @prices, @completion_times)), class: "button-red-secondary" %>

        </div>
      </div>
    </div>
  </div>
</div>